# =============================================================================
# OVHcloud Development Environment - Root Configuration
#
# This root module connects the development environment values to the
# reusable network, security and container-platform child modules.
# =============================================================================

locals {
  name_prefix = "${var.project_name}-${var.environment}"
}


# =============================================================================
# Network Module
#
# Creates:
# - One OVHcloud private network
# - One private subnet in the selected region
# =============================================================================

module "network" {
  source = "../../modules/network"

  service_name = var.service_name
  region       = var.region

  network_name = "${local.name_prefix}-network"
  subnet_name  = "${local.name_prefix}-subnet"
  subnet_cidr  = var.subnet_cidr

  ip_version       = var.ip_version
  vlan_id          = var.vlan_id
  enable_dhcp      = var.enable_dhcp
  dns_nameservers  = var.dns_nameservers
  allocation_pools = var.allocation_pools
}


# =============================================================================
# Security Module
#
# Creates:
# - One OpenStack security group
# - Zero or more ingress rules
# - Zero or more egress rules
#
# OpenStack credentials are required before this module can be planned
# or applied.
# =============================================================================

module "security" {
  source = "../../modules/security"

  region                     = var.region
  security_group_name        = "${local.name_prefix}-sg"
  security_group_description = "Security group for the ${var.environment} environment."
  delete_default_rules       = var.delete_default_rules

  ingress_rules = var.ingress_rules
  egress_rules  = var.egress_rules
}


# =============================================================================
# Container Platform Module
#
# Creates:
# - One OVHcloud Managed Kubernetes cluster
# - One Kubernetes worker-node pool
# - Optional Kubernetes API IP restrictions
#
# The Kubernetes cluster is attached to the private network and subnet
# created by the network module.
# =============================================================================

module "container_platform" {
  source = "../../modules/container-platform"

  service_name = var.service_name
  region       = var.region

  cluster_name       = "${local.name_prefix}-k8s"
  cluster_plan       = var.cluster_plan
  kubernetes_version = var.kubernetes_version

  # Use the IDs generated by the network module.
  private_network_id = module.network.network_openstack_id
  nodes_subnet_id    = module.network.subnet_id

  # Phase 1 low-cost networking configuration:
  # - No managed Gateway
  # - The private network is not used as the default route
  default_vrack_gateway              = ""
  private_network_routing_as_default = false

  node_pool_name = var.node_pool_name
  node_flavor    = var.node_flavor

  desired_nodes = var.desired_nodes
  min_nodes     = var.min_nodes
  max_nodes     = var.max_nodes

  autoscale      = var.node_autoscale
  monthly_billed = var.monthly_billed
  anti_affinity  = false

  api_allowed_cidrs = var.api_allowed_cidrs
}